apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: broken-api-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Foo is the Schema for the foos API
      displayName: Foo
      kind: Foo
      name: foos.broken.awgreene.com
      version: v1alpha1
  description: This operator makes a breaking api change between versions
  displayName: Broken API Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - test
  links:
  - name: Broken Api Operator
    url: https://broken-api-operator.domain
  maturity: alpha
  provider:
    name: Alexander Greene
  version: 0.0.0
